# Generated by Django 4.1.5 on 2023-01-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_number",
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
