# Generated by Django 4.1.5 on 2023-01-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="availabe",
            new_name="available",
        ),
    ]
