# Generated by Django 4.1.5 on 2023-01-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_availabe_product_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="productID",
        ),
    ]
